### ISSUE TITLE
Interface between Aircraft model and sample algorithm

### ISSUE THREAD

**Issue by HonDuan** [mitre/FMACM#2]
.       Do we need to send more data from Aircraft model to FIM algorithm except own position/velocity. For example, FIM algorithm needs to know flap configurations to limit the commanded speed within flap speed. So following parameters is required by FIM algorithm. Do you need to define the interface between Aircraft model and sample algorithm?

MACH/CAS crossover altitude
Alt_FAF
Ias_FAF
ias_descent
mach_descent

**Comment by sbowman-mitre** [comment]
Hi. We haven't explicitly defined an interface as it could change based on implementation, but you are certainly on the correct track. I'd say the general data requirements for the FIM algorithms are:
- current ownship state information
- current ownship configuration (for flaps and speedbrakes)
- target aircraft's latest ADS-B state from ASSAP
- predicted environmental wind and temperature information
- sensed wind information (to trigger wind-blending)
- ownship & target aircraft intent information (for ownship, this can include the extra information you mention above)

Does that help?

**Comment by HonDuan** [comment]
It is helpful. thanks
