### ISSUE TITLE
AircraftIntentFromFile Doesn't Load Latitude and Longitude of HFP file

### ISSUE THREAD

**Issue by rtsleight** [mitre/FMACM#21]
It looks like fields may have been added to the HFP file (groundspeed and bank_angle), but the HFP csv file reader in AircraftIntentFromFile doesn't know this.

The comments on the expected format do not include ground speed and bank angle:
https://github.com/mitre/FMACM/blob/dce6c55823476df0cbad60b881de481f89f3b32f/AircraftDynamicsTestFramework/AircraftIntentFromFile.cpp#L58

Modifying the following cases to be 13-16 instead of 11-14 worked for me:
https://github.com/mitre/FMACM/blob/dce6c55823476df0cbad60b881de481f89f3b32f/AircraftDynamicsTestFramework/AircraftIntentFromFile.cpp#L111-L121

**Comment by sbowman-mitre** [comment]
Ack! You are correct. We'll try to get this fixed very soon & out to you.

**Comment by sbowman-mitre** [comment]
We should be able to work on this soon. In the meantime, you can safely implement a fix on your side that /ignores/ the extra columns. Let me know if that doesn't help. Thanks!

**Comment by sbowman-mitre** [comment]
After re-reading your initial description, I realized that you already did implement a working fix on your side. Sorry I missed that before. And glad you got it working!

**Comment by sbowman-mitre** [comment]
This should be resolved now with the release of v3.3.0
