### ISSUE TITLE
The Temperature and winds from the ENV file may not be applied at the correct altitude or horizontal position

### ISSUE THREAD

**Issue by rtsleight** [mitre/FMACM#22]
The ENV file is read in by WeatherTruthByTime. The ENV time field is matched to the simulation time to get the current WeatherEstimate. This weather estimate is supposed to correspond to the wind and temperature at a given horizontal position and altitude. However, when on descent, the temperature and altitude are changing rapidly. If an aircraft is moving faster than expected, it may be at a much lower altitude (and different horizontal position) than where the wind/temp was sampled for a given time. The temperature used for converting from CAS/IAS to TAS may be relevant for an altitude 1000's of feet above or below it's actual altitude, causing the TAS to be biased and the actual ground speed of the simulation to be biased.

Example: An aircraft arrives at 28,000 ft 1 minute earlier than the nominal time in the ENV file. It's currently descending at 2465 feet/min. In the nominal flight, the aircraft was at 28,000+2465= 30,465 ft at that time. The temp in the ENV file at 30,465 ft was 227.02 K, and the temp at 28,000 ft was 231.78 K.

If the aircraft is flying 280IAS, then the TAS is calculated as 418 kts instead of 422 kts with the correct temperature. Over 100 NM, this would cause almost 10 sec of ETA error.

Ideally, we'd have some plots and results showing this. I just don't have time right now...

**Comment by sbowman-mitre** [comment]
Got it, thanks! We'll take a look and see what we come up with. We may need to also provide a WeatherTruthByDtg implementation. Not sure yet...

**Comment by sbowman-mitre** [comment]
Okay, I have working code for WeatherTruthByDistanceToGo. See attached. This class will also be part of the next source code release & I'll leave this issue open until we get that out. I have tested the code and do think it's solid, but certainly open a new issue if it causes problems.

[issue_22_code.zip](https://github.com/mitre/FMACM/files/3843639/issue_22_code.zip)

**Comment by sbowman-mitre** [comment]
Release v3.3.0 has resolved this concern. See WeatherTruthByDistanceToGo.cpp.
