### ISSUE TITLE
Issue on Aircraft model for test vector FimTv07 when descending

### ISSUE THREAD

**Issue by HonDuan** [mitre/FMACM#3]
When I run FimTv07, the spacing is kept well during the level flight. 
But during the descending, the spacing isn't kept well. I analysis the output data. It seems the aircraft control model doesn't work well. I don't know where the issue is. Would you please help us to find issue? Thanks.
Here is our analysis
1. During the descending, the own aircraft follows the vertical profile which is provided by FimTv07-1D-JET1_VFP.csv, the flight path angle is changed to 3 degree soon. Question, once the vertical profile is determined, can thrust control the speed of the aircraft? 
2. According to the document FIM MOPS - Aircraft Model WP v0.2b.pdf, equation - (51), the commanded thrust is deduced soon. But it is limited within the [minThrust, maxThrust], so the commanded thrust is the minimal thrust during the start of the descending. 
3. In the scenario, the ground speed of target aircraft is decreased, so in order to keep spacing, the own aircraft should decrease the ground speed. But during our simulation, own aircraft has the constant CAS rather than following the commanded CAS. 
4. So the ASG doesn't keep well.
5. Similar issue happens in FimTv08 during descending.

**Comment by sbowman-mitre** [comment]
Hi @HonDuan : Thanks for posting these questions (and also the ones for #4 ). The test vectors are still being completed, so we don't have the ability to respond to this quickly. Please be patient while we try to complete committee work in this area. Then we'll get back to these. Thanks!

**Comment by HonDuan** [comment]
OK, please think about the issue when you have spare time. Hope these questions don't disturb you too much. Many thanks :)

**Comment by sbowman-mitre** [comment]
Hi @HonDuan, it sounds like you are struggling with the aircraft over-speeding on the descent. There are two items to consider here. 1. Once the aircraft is at minimum thrust and still needs to decrease speed, there is a speedbrake model that gets used (see https://github.com/mitre/FMACM/blob/master/CoreII/ThreeDOFDynamics.cpp) to continue to reduce speed. Make sure that is being activated properly. 2) When implementing BadaWithCalc::getConfigForDrag(), make sure that drag is being properly returned. In particular, the input altitude should be in units consistent with your implementation.

I will also try to re-run FimTv07. If I see anything odd on our side, I'll let you know.

**Comment by HonDuan** [comment]
Thanks, I will have a try.
So far, the aircraft model is worked well and all test vectors for aircraft model is running PASS. 
We are implementing the innterface between aircraft model and sample algorithm. 
Once we get some result, I will let you know.
thanks
