### ISSUE TITLE
FlightManagementSystem if-loop necessary?

### ISSUE THREAD

**Issue by sbowman-mitre** [mitre/FMACM#6]
In #5, @HonJinghua identified some code in FlightManagmentSystem{} that looks odd. I'm reposting here as a separate issue.

The vector preCal_Wpt in FlightManagementSystem::update() in FlightManagementSystem.cpp are pushed from HPT_1 to HPT_8. So the constraint_dist are vectored starting from the endpoint in function TrajectoryFromFile::calculateWaypoints() . So precalcWaypoints[ix].constraints.constraint_dist is greater than precalcWaypoints[ix-1].constraints.constraint_dist, the condition below will always be failed.

``` c++
    for (int ix = 1;(ix if ((currDist < precalcWaypoints[ix-1].constraints.constraint_dist) &&
       (currDist >= precalcWaypoints[ix].constraints.constraint_dist)) 
    {
           this->NextWp = ix;
           break;
    }
```

Current our solution is 

``` c++
for (int ix = 1;(ix if ((currDist >= precalcWaypoints[ix-1].constraints.constraint_dist) &&
    (currDist < precalcWaypoints[ix].constraints.constraint_dist)) 
    {
        this->NextWp = 8-ix;
        break;
    }
```

**Comment by sbowman-mitre** [comment]
Hi @HonJinghua, I've evaluated this section of the code and agree that the logic is reversed. I'm glad you've found a fix that is sufficient for you needs. I do recommend that you change the 8 to a variable. You should be able to do that using: `precalcWaypoints.size()`

Let me know if that helps you or not.

**Comment by HonJinghua** [comment]
Yes, we should use the variable to replace hard code. It works! Thanks!
