### ISSUE TITLE
Question on wind prediction

### ISSUE THREAD

**Issue by HonDuan** [mitre/FMACM#7]
We encounter an issue when we running test scenario Tv09_JET1.
1. At the scenario starting, the wind vector would in five flight levels: [2900, 10000, 20000, 30000, 31000]. ft
2. The own aircraft is cruise at flight level of 31000ft, accurate altitude value is 31004ft.
3. During the simulation, the wind accuracy is checked every cycle. Once the wind error is out of tolerance, the sensed wind will be added in the wind vector, so the wind vector would be in six flight level [2900, 10000, 20000, 30000, 31000, 31004]ft 
4. The wind prediction will use five flight level’s wind data, but when we using these five flight levels of wind data [10000, 20000, 30000, 31000, 31004]ft, the predicted wind is jumped to a big value. 
5. For example, when the altitude is below 25000 ft, we use [2900, 10000, 20000, 30000, 31000] ft for wind prediction, the WindVx is about 60kt.
   But when the altitude is exceeded to 25000 ft, we use [10000, 20000, 30000, 31000, 31004] ft for wind prediction, the WindVx is more than 1000kt. 
6. I think the error is caused by the altitude data [30000, 31000, 31004] is too close to calculate the predicted wind, I just use the MATLAB to calculate the predicted wind with following simulation data.
   [Alt(ft),     Vx(kt)]= [10000, 23.92; 20000, 126.31; 30000, 189.96; 31000, 221.55; 31004, 211.88]
   The predicted Vx at 28000ft is  -1400kt

BTW, please double check if the Unit of alt in FimTv02-_-__ForeWind.csv is correct; I think it doesn’t make sense if it indicates the altitude is 35000 meter.

**Comment by sbowman-mitre** [comment]
Thanks @HonDuan . I'll take a look when I get the chance. It will probably be several days.

**Comment by sbowman-mitre** [comment]
@HonDuan : yes, we've double checked the units of altitude in FimTv02 and agree that the unit is wrong. It should be meter, not feet. Thank you. The latest updates to the test vectors will include this correction. 

I will evaluate the wind blending bug this week.

**Comment by sbowman-mitre** [comment]
@HonDuan : there are a bunch of runs for TV09. Which one in particular was showing a wind blending problem?

**Comment by HonDuan** [comment]
FimTv09-1-JET1*, we only run this test case.

**Comment by sbowman-mitre** [comment]
@HonDuan : I did re-run our FimTv09-01 case and it does not experience any large velocity values like you report.

Could there must be some misunderstanding with the wind-blending algorithm? In the example you provide, I get a reasonable value using simple linear interpolation (also using MATLAB):

``` matlab
>> data = [10000, 23.92; 20000, 126.31; 30000, 189.96; 31000, 221.55; 31004, 211.88]

data =

                     10000                     23.92
                     20000                    126.31
                     30000                    189.96
                     31000                    221.55
                     31004                    211.88

>> interp1(data(:,1),data(:,2),28000)

ans =

                    177.23
```

What interpolation scheme are you using?

**Comment by sbowman-mitre** [comment]
Actually, I wonder if you are using the wrong algorithm when updating predicted winds with sensed. The algorithm for blending predicted with sensed is a simple weighted blending algorithm. This is different than the spline-fit algorithms recommended for general wind look-up operations (not blending). See Section C.2.2.3.3 in the MOPS.

**Comment by HonDuan** [comment]
Thank you for your response.
I think we have some issue on the wind-blending. 
For example:
1. At first, Forecast Wind is 
data = [2900, 16.0; 10000, 23.92; 20000, 126.31; 30000, 189.96; 31000, 221.55];
2. Once the difference between sensored wind and predicted wind is out of tolerance, the wind should be blended before insert to wind matrix.
So the wind would be 
data = [2900, 16.0; 10000, 23.92; 20000, 126.31; 30000, 207.47; 31000,211.88; 31004, 211.88];
so the wind data at 30000 and 31000 is updated, for wind prediction we still use spline-fit algorithm but for wind blending we use the algorithm in C2.2.3.3.

**Comment by sbowman-mitre** [comment]
Yes, this sounds correct to me.

Should we close this issue or do you need to debug your simulation further?

**Comment by HonDuan** [comment]
Can be closed. thanks
