### ISSUE TITLE
Question on IM turn

### ISSUE THREAD

**Issue by HonDuan** [mitre/FMACM#8]
1. How to calculate the turn point in the case of shorten length scenario?
   I think you have provided the algorithm in MATLAB for vector off of original route case, but for the remain on original route case, it use the same algorithm?
2. How to force the own aircraft vector off in the aircraft model?
   I think when the IM type is IM turn, the own aircraft should be forced to vector off its original route in order to lengthen or shorten flight path. But the horizontal guidance is provided by the *HFP.csv which is not changed during the simulation. How to drive the aircraft model to turn as we expected? 

Thank you:)

**Comment by sbowman-mitre** [comment]
1. Yes, the IMTurn operation is simulated entirely in the MATLAB code provided. For cases in which the aircraft is always following the Intended Flight Path horizontal path, the C++ code is used.

**Comment by sbowman-mitre** [comment]
2) We have not provided an integration of the MATLAB & C++ capabilities. So, the C++ code is not currently capable of performing the IMTurn operation for stretching or compressing the horizontal path. Of course, you are welcome to modify the code to fit your purposes, so feel free to do what you need to make the simulation suite your testing needs.
