### ISSUE TITLE
Issues in this week

### ISSUE THREAD

**Issue by HonDuan** [mitre/FMACM#9]
1. Tv11, in this test vector, final approach spacing is verified. I saw from the NavDB data, for the intercept cases the merge waypoint is provided in the NavDB, so it seems we don't need to calculate the merge waypoint. But in the real cases, how the final approach spacing works? How to determine the intercepted aircraft for own and target aircraft? Do we need to know the final approach course so that we can determine which one is on final approach or not?
2. In some test cases, the TOAp[sec]/ TOAv[sec] in *.TTV between two consecutive records is greater than 30s, so the established track is dropped due to long duration of coasting. So would you please to reduce the coast time in order to keep the stable track? 
   Please see FimTv09-4-JET2_TTV.csv, FimTv09-7-JET3_TTV.csv, FimTv09-19-JET1_TTV.csv
3. We have been running some close loop test cases (at least one case for Tv07, 08, 09, 11), it seems the aircraft model and sample algorithm really work. Thank you all for the great efforts on FIM MOPS.

**Comment by sbowman-mitre** [comment]
Good, we are glad to hear that the closed-loop cases are working well! One of us will get back to answer your questions soon.

**Comment by delliott-mitre** [comment]
For #1, all waypoints except the start and end of the final approach course will be removed to represent the IFPI for both aircraft.  The starting point of each aircraft will allow the FIM equipment to determine if ownship or traffic are on final approach or on intercept.  These updates will be provided in the next update to the test vectors and figure G-17 in the mops will be updated accordingly.

For #2, states will be added to test vectors with large data gaps to prevent dropped tracks by assap.  We will review all test vectors for this issue, but please forward the filenames for any additional test vectors with this issue as you find them.  These updates will be provided in the next update to the test vectors.

**Comment by HonDuan** [comment]
Here are all we knows have this kind of issues:
FimTv08-5-JET5_TTV.csv
FimTv11-7-JET3_TTV.csv
FimTv11-10-JET4_TTV.csv
FimTv11-12-JET4_TTV.csv
FimTv11-18-JET6_TTV.csv

**Comment by delliott-mitre** [comment]
I have identified these test vectors with data gaps that are too large.  A few of them have more than one instance of large data gaps.  I am currently in the process of correcting:
Tv08
¨ FimTv08-3-JET3_TTV.csv
¨ FimTv08-4-JET4_TTV.csv
¨ FimTv08-5-JET5_TTV.csv 
Tv09
¨ FimTv09-1-JET1_TTV.csv
¨ FimTv09-2-JET1_TTV.csv 
¨ FimTv09-3-JET1_TTV(t).csv 
¨ FimTv09-20-JET1_TTV.csv 
¨ FimTv09-4-JET2_TTV.csv 
¨ FimTv09-5-JET2_TTV.csv
¨ FimTv09-6-JET2_TTV(d).csv    ¨ 2 times
¨ FimTv09-7-JET3_TTV.csv   ¨ 2 times
¨ FimTv09-9-JET3_TTV(t).csv    ¨ 2 times
¨ FimTv09-9-JET3_TTV(d).csv
¨ FimTv09-11-JET4_TTV.csv  ¨ 2 times
¨ FimTv09-12-JET4_TTV(t).csv   ¨ 2 times
¨ FimTv09-12-JET4_TTV(d).csv 
¨ FimTv09-15-JET5_TTV(t).csv   ¨ 2 times
¨ FimTv09-15-JET5_TTV(d).csv
¨ FimTv09-16-JET6_TTV.csv 
Tv11
¨ FimTv11-5-JET2_TTV.csv 
¨ FimTv11-7-JET3_TTV.csv 
¨ FimTv11-10-JET4_TTV.csv 
¨ FimTv11-12-JET4_TTV.csv 
¨ FimTv11-18-JET6_TTV.csv  2 times

**Comment by delliott-mitre** [comment]
These and other updates are now available for download from the RTCA site.

Please feel free to log into your RTCA Workspace account and go to either the “FRAC – New FIM MOPS DO-nnn/ED-236” folder at the top level of the RTCA SC-186 Workspace, or to the “FIM MOPS Current Draft” folder under the SC-186 WG-4 Workspace to retrieve the ZIPX Test Vector file uploaded and dated 7-24-2015.
